name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_message: "chore: update ${filename}"
          config_timezone: Asia/Ho_Chi_Minh
          template: classic
          base: header, activity, community, repositories, metadata
          config_order: base.header, base.repositories, base.activity+community, isocalendar, music
          output_condition: skip-if-only-metadata-changed
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot, vba, tsql, scss, gherkin, vim, vim script, handlebars, XSLT
          retries_output_action: 5
          retries_delay_output_action: 120

  delete-runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 2
          keep_minimum_runs: 2
